[connections.gsheets]
type = "service_account"
project_id = "ninja-guild-bot"
private_key_id = "KODE_ID_ANDA"
private_key = """-----BEGIN PRIVATE KEY-----
ISI_KUNCI_ANDA_YANG_PANJANG
-----END PRIVATE KEY-----"""
client_email = "ninja-guild-bot-869@ninja-guild-bot.iam.gserviceaccount.com"
client_id = "ANGKA_ID_ANDA"
auth_uri = "accounts.google.com"
token_uri = "oauth2.googleapis.com"
auth_provider_x509_cert_url = "www.googleapis.com"
client_x509_cert_url = "www.googleapis.com..."
