[connections.gsheets]
type = "service_account"
project_id = "ninja-guild-bot"
private_key_id = "9ac509b67734b0534cdb7870e206f46d1a90cbb8"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCUxrZvQGiSv73G
kbouBSInceAnf3KWwqL/mzzNY5g2TcnhQ4UDgWStMLhWCzo3ipswT1TJOoK3HvAc
IRP50xO81FSeZZFW9+LmqSTQszT8PDG6YDzurboJaUTy6GWSrgbN5DdIqgNbMYlR
wWqn8lhQtHF3S5JLg8exfw64qZRXO6JfLwlUm3kUMcXQgMl+qr8O/vAtGiKj8IFw
P2tPHR9D/zoOBPzGLvUaGk7dSDZSv+kDBDguvTYO023MO4S153XopHT9ro/Uc4tE
2ivIu2FN+500Ofy2n3rxOASI0WUBrI/KbfaimeXzayiKIIW+tf8wT6TZgzOmUjCH
Cw4P9yGRAgMBAAECggEABJGPk54COBNsQ/dApN4ifNyZ2gynW6rRb5D4ToRS7cP4
wZKduIxWJ51Z48aHfKIkftjIzT8fOXlZPTvkzaSmNAO/L3gF/QoyrQufpksCgwZk
Lol7BYdPMa/KXr01NUpjyhnKetBBtyCvy1Npr4uZG61W2Kd48Bm1XaV9sbz/YahW
otjn44uufojP/VjsmJiQeqeHgxhvaMu1zAfzOFoYramZAzPC2cHTdeC8+gPN1EQz
73LxBJv5bFxpLm2iVhXC4TjZk0AtrB+78iJe/VApmc1MNNc1q299uAeki6OZfrCB
atZkyeyBFtwv2iV+5P7Y+yoHiJlfidJ2iQctfLcauQKBgQDQJHX5YW7f4/i6pAtS
lE648g1NeVZ/xV8+accw+By5sm+7eokUftoRsc0lDbYP7gqKtwRgvzKr9db868Zj
Nirh9VdHRBGgHnoIngEckxD6bfx/X2EFqUAlEIoXLzi7IxFCRPWVeU7lss+2qj42
RodFJqsZ08g1q2IS9ui1gVTgVQKBgQC2++DY8J8DoaaQZonzoyr6EHoKrSgAFM4e
GusP4OpCXQ2o1WesztiU1RmZp8idEREvRntMVKNnZD+6GozSKKcFa1qPmLLDBf+b
eTRgeF2EdGThIxbZVNdVbgWP0Yg8sOBcjTCu+GizoO4JlnFImfz+F0CZMHuwrakn
O1Mw0bkITQKBgE5qDg//hvfOOPyHpMRdnzLJ7f0MA2xrfTBURXjLYHcNJE7rIQ2Z
pKoZ5AFbowVpVotf28RfA8YI/g+W+8yQsaMi/NiaalF6adspO536QeE24nNSCYlK
dCICkyOc5LCLy4q91A+V/gVHUj2s8XcdJwUERl2ajci6Yl5mqtEGgmVpAoGBAI9H
IoQ7xQce6EFhSNuRA/HSPP1nIE8P+2TvRuekAUn9eticYRWa0VOYmPcLvbXey0nt
MlZOX7RxdsTOTT2xvzYrHTobIr46UC749N4k4XT5fpQa2aVLHWEzSP+X3clH5iYS
F/CpabJdbIXtWr6ydLqwklBg+jkZgb3KYhVz4iJxAoGBAIlaZ8h9OB6TTPYjuHT5
J43zBXUXdo1V1CTCG0LKg/toIc9qmtZm3UUz+quvwRB1mJMteu98QvAVLFkXNo62
N2A4ncF63Ym4EWb2pClBoiVOeBclVgOCA1PTxo43jrWPOaVYp5vrnO3c3RKIHKUx
DCy7Z3eBWMlygSVy5esORGY8
-----END PRIVATE KEY-----"""
client_email = "ninja-guild-bot-869@ninja-guild-bot.iam.gserviceaccount.com"
client_id = "102726001485388755443"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/ninja-guild-bot-869%40ninja-guild-bot.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
