[connections.gsheets]
type = "service_account"
project_id = "9ac509b67734b0534cdb7870e206f46d1a90cbb8"
private_key_id = "KODE_ID_ANDA"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCKybwL8QI3ySbB
S/quqrLhXrrdH8oMCD/6bS/xJSm7mDo+NQ8SzEJwR/xvi7G/GANUjV/fOKENb5xe
Z27Rkd7G+zYMfthLd165BqH5Z91ZwDu8ijLCR76LjoWqkCBrNH4JGGIxSVdwp+IK
vVMX1OBJ+qQSEvYviqJSkGILkPygQEewOPlCNydIgpNZUBDobSB0zCHx6HhGTnBA
MzAVz2lYbu8QlUdZQ4vIyyQf1J9t8/yGP+GpPkPPyDjsN/7pkDmXtD2gTM1utv7n
6ZfgHUvrx37Uzuo1ELO5DKjSFnFU2y1kV33MwuTa3scScznf6aTJK2adgkROYLbD
trY1BYw9AgMBAAECggEADczlf/fPv/r7zuNejUO3/yT2RnVEwqbcsGrEW6GAYYD6
OaP5AxDV172wt5QXxpKoB3OkrC5AsB9VrdAcetubCq+BaQNWlUUiDBqWvJVmsz1O
3f6NRuLvat0Zzs3/YJRFpriKpa/58TUgYEUBytrbZT/LqhMXRmmYnnEbmV7UtUfJ
hSCuC1gN1lzykzbcEuEOS/Zn4AqmTAyYL1f3TWo5SC3aMTq0zs9SoJrgZDeLJ5AB
RI9ZLMxrsouil5F1kDwLTwEbxgMUFw/pSKf0lvBU9MmOibE60gkgSudPGTNBjq+C
Phe5kPIhh9a8yb0XCMC3CO018L87CnlUs9tXJS+GGQKBgQDAiVocnwoK8z7ObPK7
psvDbat2zxT5vtjXESN8R7iUt+mJov1yhT+JFBRLt1P9lF3M/tXQWsKdfVYBffCO
iNVe/R3lktATELAjt5ZhHOI7kGeodURTrU7ZsG0PTfzgjdDdPvd66YD3KspFy7Ww
Co3VNkYlLZe2vK4ncB0wPhPkZwKBgQC4iPe4yItfLYft4H8ykNxfvNp815BU6cPX
uektxDwEpG5cezPQKMkAiPiyyJ6eD7oIRneKDznDpGsnMtPSQlbvBDfmsBAXSABm
ai5KXpNMtJS9ccCEinumzmudKZogAkPDFIKsTk4Pwt+ar/k+6YIONNcbBOnNReQk
bX/K0luDuwKBgBTJv7T/ZvIvuURIdxzTsYR0PuMhEL62YGs4KoCsrb1A7jIyKvNG
d8mxJU/Xh3YFousTSLqqUgD3G2Yl1udM1tzer2+uHlEwqBPzKoVpvPN5b/e8UZhH
ShAvAFd6sCb+qOJ6ffYDaC1HrXdDu2Y6fX3b0k8JUSwlyxfu/vfKfBNZAoGBAJNg
6J+OoyjnnzkPY+cJpMddeA3ex6nZbQz8sMtZfymh/XYk+3OTLz0bJ6z55xyLqOL1
DIGZuWOUC/QpdtzlGLMZ5l96W8+MNK2WvdOthuzrCCPpFn2EcE7/axkA4dQQmvfR
iK9+dn/F/nl3c5OYQMOB1g4BNY049YVWYoqkyGwDAoGAKWAPA6M4SKXTk6pLzRB3
jQgyUGR6rE4pWx9QlCj42R9mf8dQhn66XEINNCyUEQmGx7i8Of3sq3NGWYaU8Cr3
lNL80sOENnqNpq50e0PbNQlNONLc9pmo/uUYFtZdGtdsLQc4wK9JPxvrig7Zc0YJ
ePWGcbE4HFe+D9NEGfU07eA=
-----END PRIVATE KEY-----"""
client_email = "ninja-guild-bot-869@ninja-guild-bot.iam.gserviceaccount.com"
client_id = "ANGKA_ID_ANDA"
auth_uri = "accounts.google.com"
token_uri = "oauth2.googleapis.com"
auth_provider_x509_cert_url = "www.googleapis.com"
client_x509_cert_url = "www.googleapis.com..."
